# syntax=docker/dockerfile:1
# Pinned base: python 3.12.8 slim bookworm (update digest when rebasing images).
FROM node:22-bookworm-slim AS admin-ui
WORKDIR /build/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend ./
RUN npm run build

# Toolchain copied into the Python runtime for stdio upstreams (npx/node).
FROM node:22-bookworm-slim AS node-runtime

FROM python:3.12.8-slim-bookworm@sha256:2199a62885a12290dc9c5be3ca0681d367576ab7bf037da120e564723292a2f0 AS builder

WORKDIR /build
ENV PIP_NO_CACHE_DIR=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

# Install fully pinned, hash-verified dependencies from the committed lockfile
# export (generated by `uv export`; see docs/DEPLOYMENT.md). --require-hashes
# makes the build fail closed if any dependency or transitive pin is missing or
# tampered with, giving a reproducible, vulnerability-scannable image.
COPY requirements.txt ./
RUN pip install --upgrade pip \
    && pip install --require-hashes --no-deps -r requirements.txt

# Install the application itself (deps already locked above; --no-deps keeps the
# install reproducible and avoids re-resolving against PyPI).
COPY pyproject.toml README.md ./
COPY src ./src
RUN pip install --no-deps .

FROM python:3.12.8-slim-bookworm@sha256:2199a62885a12290dc9c5be3ca0681d367576ab7bf037da120e564723292a2f0 AS runtime

RUN groupadd --gid 10001 concierge \
    && useradd --uid 10001 --gid 10001 --create-home --shell /usr/sbin/nologin concierge

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin/concierge /usr/local/bin/concierge
COPY pyproject.toml README.md ./
COPY src ./src
COPY config ./config
COPY examples ./examples
COPY --from=admin-ui /build/frontend/dist ./admin-ui

# Stdio upstreams spawn inside this container. Copy Node.js from a dedicated
# stage and recreate npm/npx symlinks (plain COPY dereferences symlinks and
# breaks npm-cli.js relative imports). Python (python -m …) is already
# available from the runtime base image.
COPY --from=node-runtime /usr/local/bin/node /usr/local/bin/node
COPY --from=node-runtime /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN ln -sf ../lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
    && ln -sf ../lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx

# PyPI MCP servers commonly document `uvx mcp-server-*` (Astral's npx equivalent).
# Pin version; digest: sha256:9874eb7afe5ca16c363fe80b294fe700e460df29a55532bbfea234a0f12eddb1
COPY --from=ghcr.io/astral-sh/uv:0.8.22 /uv /uvx /usr/local/bin/

RUN chown -R concierge:concierge /app

USER concierge
EXPOSE 8765

# Liveness/readiness routes are provided by the gateway (see P1-6).
HEALTHCHECK --interval=30s --timeout=3s --start-period=15s --retries=3 \
  CMD python -c "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8765/healthz')" || exit 1

# uvicorn forwards SIGTERM to the lifespan shutdown hook, which drains in-flight
# calls before exiting (see src/concierge/server/app.py). Running concierge as
# PID 1 ensures the orchestrator's SIGTERM reaches the app for a graceful
# rolling restart.
ENTRYPOINT ["concierge"]
CMD ["--config", "config/gateway.example.yaml"]
